create table tbl_address (id integer generated by default as identity, address_detail varchar(255) not null, address_type varchar(255) not null, other_description varchar(255), title varchar(255), zip_code_id integer not null, primary key (id));
create table tbl_country (id integer generated by default as identity, code varchar(255) not null, dial_code varchar(255) not null, name varchar(255) not null, primary key (id));
create table tbl_user (id integer generated by default as identity, birth_date date, email_address varchar(255) not null, first_name varchar(255) not null, last_name varchar(255) not null, phone_number varchar(255) not null, primary key (id));
create table tbl_zip_code (id integer generated by default as identity, district varchar(255) not null, postal_code varchar(255) not null, province varchar(255) not null, region varchar(255), street varchar(255) not null, country_id integer not null, primary key (id));
create table user_address (user_id integer not null, address_id integer not null, primary key (user_id, address_id));


INSERT INTO "PUBLIC"."TBL_COUNTRY" ("ID", "CODE", "DIAL_CODE", "NAME") VALUES (1, 'TR', '+90', 'TURKEY');
INSERT INTO "PUBLIC"."TBL_ADDRESS" ("ADDRESS_DETAIL", "ADDRESS_TYPE", "OTHER_DESCRIPTION", "TITLE", "ZIP_CODE_ID") VALUES ('X CADDESI Y SOKAGI', 'HOME', 'CAMININ KARSISI', 'HOME', 1);
INSERT INTO "PUBLIC"."TBL_USER" ("BIRTH_DATE", "EMAIL_ADDRESS", "FIRST_NAME", "LAST_NAME", "PHONE_NUMBER") VALUES ('1994-11-02', 'habiphakan@live.com', 'Habip Hakan', 'isler', '5061644665');
INSERT INTO "PUBLIC"."TBL_ZIP_CODE" ("DISTRICT", "POSTAL_CODE", "PROVINCE", "REGION", "STREET", "COUNTRY_ID") VALUES ('Pendik', '349195', 'Istanbul', 'Marmara', 'Kurtkoy', 1);
INSERT INTO "PUBLIC"."USER_ADDRESS" ("USER_ID", "ADDRESS_ID") VALUES (1, 1);
