create table tbl_address (id integer generated by default as identity, address_detail varchar(255) not null, address_type varchar(255) not null, other_description varchar(255), title varchar(255), zip_code_id integer not null, primary key (id));
create table tbl_country (id integer generated by default as identity, code varchar(255) not null, dial_code varchar(255) not null, name varchar(255) not null, primary key (id));
create table tbl_user (id integer generated by default as identity, birth_date date, email_address varchar(255) not null, first_name varchar(255) not null, last_name varchar(255) not null, phone_number varchar(255) not null, primary key (id));
create table tbl_zip_code (id integer generated by default as identity, district varchar(255) not null, postal_code varchar(255) not null, province varchar(255) not null, region varchar(255), street varchar(255) not null, country_id integer not null, primary key (id));
create table user_address (user_id integer not null, address_id integer not null, primary key (user_id, address_id));


